### ISSUE TITLE
camunda:string is not handled as expected

### ISSUE THREAD

**Issue by rjayasinghe** [bpmn-io/moddle-xml#13]
Hi!

I am currently trying to define a moddle that is able to parse and render the following xml construct:

```    
<bpmn2:extensionElements>
  <camunda:field name="field">
    <camunda:string>transLock</camunda:string>
  </camunda:field>
  <camunda:field name="value">
     <camunda:string>(Yes)</camunda:string>
  </camunda:field>
</bpmn2:extensionElements>
```
In the camunda-moddle.json I have added two element definitions for Field and String:
```
    {
      "name": "Field",
      "properties": [
        {
          "name": "name",
          "isAttr": true,
          "type": "String"
        },
        {
          "name": "nodeValue",
          "isBody": true,
          "type": "String"
        }
      ]
    },
    {
      "name": "String",
      "properties": [
        {
          "name": "value",
          "isBody": true,
          "type": "String"
        }
      ]
    },
```

When I define the moddle like this an error is thrown during deserialization to XML:

```
TypeError: value.search is not a function
    at BodySerializer.build (http://localhost:9013/index.js:69120:39)
    at http://localhost:9013/index.js:69334:38
    at arrayEach (http://localhost:9013/index.js:30098:9)
    at http://localhost:9013/index.js:31436:9
    at ElementSerializer.parseContainments (http://localhost:9013/index.js:69322:3)
    at ElementSerializer.build (http://localhost:9013/index.js:69169:10)
    at http://localhost:9013/index.js:69363:30
    at arrayEach (http://localhost:9013/index.js:30098:9)
    at http://localhost:9013/index.js:31436:9
    at http://localhost:9013/index.js:69351:7
```
The orginal code location where this error is thrown is in moddle-xml in writer.js:154
So it appears to me that a camunda:string is not detected as a moddle-element and is handled as a native JS string which leads to the error above.

IMHO moddle seems to have difficulties to mix identically named elements from different namespaces correctly. Do you have any suggestions how we can work around this issue in our moddle.json descriptor?

Best Regards,
Robin

**Comment by nikku** [comment]
I see two issues with your moddle descriptor:

* Elements inside `<extensionElements>` should have to have the super class `Element` (cf. [camunda-bpmn-moddle](https://github.com/camunda/camunda-bpmn-moddle/blob/master/resources/camunda.json#L585)). This is because the element may have a list of child elements of type `Element`.
* Moddle does not currently support elements that have JUST a body property. That is why defining a type `String` with `isBody` does not work may not work. The proper way to do this is by defining the `string` tag as a property of field (again, cf. [camunda-bpmn-moddle](https://github.com/camunda/camunda-bpmn-moddle/blob/master/resources/camunda.json#L603)).

**Comment by rjayasinghe** [comment]
Hi!

Thanks for the quick reaction. It does not answer my question completely, however. I took over the element definitions for "Field" from the mentioned camunda-bpmn-moddle json-File and adapted my code accordingly.
I still see the same error, when I define the camunda:string type in the moddle. When I remove that element from the moddle.json the XML file cannot be imported correctly into the bpmn.js  modeler. An error is reported that the type camunda:string is not known.

The screenshot shows the problem that rises when serializing a camunda:string element.
<img width="823" alt="bpmn-js_modeler_demo_und_notizen" src="https://cloud.githubusercontent.com/assets/1537697/13073697/62eefa0c-d4a0-11e5-9a81-b1dca904cb8e.png">

Is there anything else besides the extensions in the camunda-moddle.json that I have to do in order to introduce new elements? Is there any documentation available that shows how to write and extend moddle meta-models?

Best Regards,
Robin

**Comment by nikku** [comment]
I have a few pointers for you, even though I have to admin we may miss some pieces of documentation there.

* [moddle descriptor documentation](https://github.com/bpmn-io/moddle/blob/master/docs/descriptor.md)
* [moddle test suite](https://github.com/bpmn-io/moddle/tree/master/test), includes a lot of models as well as accompanying test cases
* [moddle-xml test suite](https://github.com/bpmn-io/moddle-xml/tree/master/test), includes import / exports related test cases and should give you a clue how the meta-model definition influences XML import / serialization
* [bpmn-moddle test suite](https://github.com/bpmn-io/bpmn-moddle/tree/master/test) and [camunda-bpmn-moddle test suite](https://github.com/camunda/camunda-bpmn-moddle/tree/master/test) may be worth checking out, too.

If you need help on the details, please provide us with a failing test case (read or write) as part of a pull-request.

**Comment by rjayasinghe** [comment]
Writing a failing testcase makes a lot of sense. I'll see if I find the time for that.

Thanks again for your timely response!
