### ISSUE TITLE
Empty <text> tags are removed when exporting

### ISSUE THREAD

**Issue by ricardomatias** [bpmn-io/moddle-xml#18]

**Comment by nikku** [comment]
How to reproduce this?

**Comment by MrMariusR** [comment]
Hello,

For example, I created a rather simple dummy DRG example to reproduce this case. You have the initial xml code in the diagram_1 - step1.txt attached file. When I open Modeler again and make some changes in the first decision table, on the second rule in my test case, you can see in the second file attached that the text tag is now missing in the second decision table for the last rule (vice versa when I change initially the second table, it breaks the last rule of the first table ) - I hope this is helpful...


[diagram_1 - step2.txt](https://github.com/bpmn-io/moddle-xml/files/688474/diagram_1.-.step2.txt)


[diagram_1 - step1.txt](https://github.com/bpmn-io/moddle-xml/files/688463/diagram_1.-.step1.txt)

**Comment by nikku** [comment]
Closed in favor of https://github.com/camunda/camunda-modeler/issues/492.
