### ISSUE TITLE
Don't throw an exception when serializing non-namespace elements

### ISSUE THREAD

**Issue by nikku** [bpmn-io/moddle-xml#24]
This allows us to write elements without declared namespaces as seen in the following XML: 

```xml
<ns:foo xmlns:ns="...">
  <Bar/>
  <FooBar/>
</ns:foo>
```

__Note:__ Technically these elements [have namespaces](http://www.rpbourret.com/xml/NamespacesFAQ.htm#schema_2), these won't be recognized by this library though until #23 is implemented. We'll however be able to pass them through during `read -> modify -> write` roundtrips.

**Comment by philippfromme** [comment]
When combined with #23 the test case for generic, non-ns elements fails. Maybe we can have a look at this together.

**Comment by nikku** [comment]
#23 is not meant to be merged, as it breaks the serialization of non-prefixed elements. Regardless, we can still have a talk sometime, if needed.

**Comment by nikku** [comment]
Cf. my [updated comment on #24](https://github.com/bpmn-io/moddle-xml/issues/23#issuecomment-340224009).
