### ISSUE TITLE
Console messages on warning and error

### ISSUE THREAD

**Issue by paed01** [bpmn-io/moddle-xml#28]
I have a question regarding the following lines in reader:

https://github.com/bpmn-io/moddle-xml/blob/a199744087199e578ef12c082aa7aaf9c3d0d4d0/lib/reader.js#L642

Is there a reason to write warnings and errors to console when they passed by `addWarning` or thrown respectively?

**Comment by nikku** [comment]
I guess that is only there for debugging reasons. Happy to ditch the warnings or wrap them in a conditional block.

```javascript
if (process.env.NODE_ENV !== 'PRODUCTION') {`
   // log
}
```

block.

**Comment by nikku** [comment]
If you want to, file a PR for this.

**Comment by nikku** [comment]
Note: We'd need to remove the logging statements on the writer, too.

That, however does log stuff that is not being exposed yet 😢.

**Comment by FlexiGit** [comment]
Any news on this issue?

Imho it's bad design for a library to write to the console at all. Either the error should be handled completely or thrown. The consuming application can then decide what to do with error.

**Comment by nikku** [comment]
> Imho it's bad design for a library to write to the console at all. Either the error should be handled completely or thrown. The consuming application can then decide what to do with error.

I 100% agree with you.

You may propose your improvement in a [pull request](https://help.github.com/en/articles/about-pull-requests) to improve the situation.

**Comment by FlexiGit** [comment]
Here you are: #37
