### ISSUE TITLE
Can you explain QName validation?

### ISSUE THREAD

**Issue by ealexhaywood** [bpmn-io/moddle-xml#41]
Hi all,

I was wondering if you could explain the reasoning behind the recently added QName validation?  This has caused breaking changes in our application.  Specifically, the block

```
// for QName validation as per http://www.w3.org/TR/REC-xml/#NT-NameChar
        if (!/^([a-z][\w-.]*:)?[a-z_][\w-.]*$/i.test(id)) {
          throw new Error('illegal ID <' + id + '>');
        }
```

So it seems we have elements with bad IDs, but should this prevent them from being added to the diagram?  This also took a while to discover since this error is bubbled up as a warning in bpmn-js instead of an error.

We were using UUIDs as the element ID, but it looks like since those contain `-` hyphens, that is considered bad XML?  Maybe I'm misinterpreting the w3 spec that's in the code comment.

**Comment by nikku** [comment]
We are parsing XML after all and the quoted line validates the XML-compliantness of IDs.

This is relevant in other places that can then rely on IDs not containing malicious characters, for instance.

Could you share a diagram that fails the validation? I'd like to double check whether we did something wrong here.

**Comment by ealexhaywood** [comment]
There's not much to show.  We use UUIDs for the `id` attribute of an element, e.g. 

`<exclusiveGateway id="8d9ba236-9109-47ca-924a-767817c69578" name="a task"></exclusiveGateway>`

I just wanted to ask what you recommend using for IDs if UUIDs are not valid.  Example XML:

```
<?xml version="1.0" encoding="UTF-8"?> 
<definitions id="Definition"
             targetNamespace="http://www.example.org/MinimalExample"
             typeLanguage="http://www.java.com/javaTypes"
             expressionLanguage="http://www.mvel.org/2.0"
             xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL"
             xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
             xs:schemaLocation="http://www.omg.org/spec/BPMN/20100524/MODEL BPMN20.xsd"
             xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI"
             xmlns:dc="http://www.omg.org/spec/DD/20100524/DC"
             xmlns:di="http://www.omg.org/spec/DD/20100524/DI"
             xmlns:tns="http://www.jboss.org/drools">

  <process processType="Private" isExecutable="true" id="com.sample.HelloWorld" name="Hello World" >
    <exclusiveGateway id="8d9ba236-9109-47ca-924a-767817c69578" name="a task"></exclusiveGateway>
  </process>
  <bpmndi:BPMNDiagram>
    <bpmndi:BPMNPlane bpmnElement="Minimal" >
      <bpmndi:BPMNShape bpmnElement="8d9ba236-9109-47ca-924a-767817c69578" id="BPMNShape_8d9ba236-9109-47ca-924a-767817c69578">
        <omgdc:Bounds x="15" y="91" width="48" height="48" />
      </bpmndi:BPMNShape>
    </bpmndi:BPMNPlane>
  </bpmndi:BPMNDiagram>
</definitions>
```

**Comment by nikku** [comment]
We are doing it wrong. That's it. Thanks for reporting.

**Comment by ealexhaywood** [comment]
No problem, thanks @nikku !

**Comment by nikku** [comment]
The spec clearly states `-` is a perfectly valid part of the name: https://www.w3.org/TR/REC-xml/#NT-NameChar

**Comment by nikku** [comment]
Rewind. The issue is not the fact that you use `-`. The issue is that your UUIDs start with a number which is indeed not a valid QName start character: https://www.w3.org/TR/REC-xml/#NT-NameStartChar

You'd need to prefix your UUIDs with `_`, a pattern that we see often in our tools.

**Comment by guanchaoli** [comment]
@nikku we moved from previous versions to the current version and we are facing the same problem. Most of our ids **start with a number**, while the regex you use does not allow it. We will need to rename all the tags id in the XMLs with a leading '_'.

Is it possible to allow digits as the leading character for you? I guess many people are facing the same situation as us.

**Comment by nikku** [comment]
The goal of this library is to consume and produce valid XML. If you're generating XML yourself _you must generated proper IDs_, cf. https://github.com/bpmn-io/moddle-xml/issues/41#issuecomment-519638542. 

Not using proper IDs will break basic XML schema validation and tool exchange.

On the other hand strict ID validation during import allows tools to use them as _safe identifiers_. 

Many tool vendors do the following to allow UUIDs: 

* Prefix the UUID with a `_`
* Prefix the UUID with another XML compliant qualifier

**Comment by nikku** [comment]
What is your use-case for this library?

**Comment by guanchaoli** [comment]
Hi, you are right. We should follow the XML restrictions. Thanks for the explaining!
