### ISSUE TITLE
[low priority] test regex for valid identifier names is not correct

### ISSUE THREAD

**Issue by adroste** [bpmn-io/moddle-xml#55]
https://github.com/bpmn-io/moddle-xml/blob/da22aa1cef8160eef2b641bfa0bb2e6c14f30867/lib/read.js#L133

Despite the fact that ids cannot start with numbers what caused some headaches in my current project, I noticed that it's not fully spec compliant.

A few test cases:

1. `Foo:` is not accepted
2. `Ä` (0xc4) is not accepted
3. `a::` is not accepted
4. `a:b:c` is not accepted
... and so on

### Why check anyway?

What is the reason to perform this check? Ids are always(?) a value of a property. As long as they use the defined encoding (utf-8 for instance) and don't include control characters, it should be fine.
Ids starting with a number would also be ok then (non prefixed uuidv4, ids, ...).

**Comment by nikku** [comment]
The library targets XML and thus, what is a valid ID is determined by the XML standard. Schemas for XML documents usually reuse the `xsd:ID` type for IDs, cf. the relevant [BPMN 2.0 spec document](https://www.omg.org/spec/BPMN/20100501/Semantic.xsd):

```xml
<xsd:complexType name="tBaseElement" abstract="true">
  ...
  <xsd:attribute name="id" type="xsd:ID" use="optional"/>
  ...
</xsd:complexType>
```

We assume that any sane XML schema operates under similar constraints. 

If you found IDs that are valid according to the `xsd:ID` type and not accepted yet, feel free to open a PR to improve our validation regex.
