### ISSUE TITLE
Element body text shouldn't be trimmed if they are not whitespace-only

### ISSUE THREAD

**Issue by davidfanca** [bpmn-io/moddle-xml#58]
When I imported a bpmn xml, the body of text elements were always trimmed.
For example, if I have the "Subject" element in my bpmn XML, the body text of the "Subject" element will be trimmed from "  
 Test   " to "Text" after loading the xml to BPMN Viewer.
**_<MyNS:property name="Subject">   Test   </MyNS:property>_**

This is not good because we need the leading/trailing space in out application.

This issue was introduced by the commit below.
[chore(reader): trim whitespace-only text](https://github.com/bpmn-io/moddle-xml/commit/bc29ecc7f78f210929dc3211535524c7598af0d4)
![image](https://user-images.githubusercontent.com/17060198/114231934-1f328900-9949-11eb-974e-65ead315c457.png)

As per the title of the commit, the commit should only trim whitespace-only text, but actually it always trims the body text regardless they are whitespace-only or not.

**Comment by nikku** [comment]
Thanks for reporting this bug. Would you like to contribute a PR that adresses this issue?

**Comment by davidfanca** [comment]
Thank you for your quick response. We would like to contribute a PR to address this issue soon.

**Comment by nikku** [comment]
Thanks. Looking forward for it.

**Comment by davidfanca** [comment]
I will create a PR today

**Comment by drrnkin** [comment]
Thanks for the quick response @nikku .  Any estimate of when this will get into the next release?

**Comment by nikku** [comment]
Released with `v9.0.5`.
