### ISSUE TITLE
`xml:lang` attribute serialized without namespace prefix

### ISSUE THREAD

**Issue by hanshuebner** [bpmn-io/moddle-xml#62]
__Describe the Bug__

When a model element uses a standard attribute with the `xml:` prefix, the attribute is parsed correctly, but the prefix is lost when serializing the model using `toXML`.

__Steps to Reproduce__

This code:

```javascript
import { Moddle } from 'moddle';
import { Reader, Writer } from 'moddle-xml';

const model = {
    name: "test",
    types: [
        {
            name: "test",
            properties: [
                {
                    name: "xml:lang",
                    isAttr: true,
                    type: "String"
                },
                {
                    name: "body",
                    isBody: true,
                    type: "String"
                }
            ]
        }
    ]
};

const test = async () => {
    const moddle = new Moddle([ model ]);
    const reader = new Reader(moddle);
    const xml = `<test xml:lang="en">Testing</test>`;

    const { rootElement } = await reader.fromXML(xml, reader.handler('test'));

    const writer = new Writer({ format: false, preamble: false });
    const result = writer.toXML(rootElement);
    return result;
}

test()
    .then(result => console.log('result:', result))
    .catch(error => console.log('error:', error));
```

produces the following output:
```shell
$ node index.js
result: <test lang="en">Testing</test>
```

__Expected Behavior__

The program should reproduce the prefix `xml:` on the lang attribute (`<test xml:lang="en">Testing</test>`).

__Environment__

- Host (Browser/Node version), if applicable: Node v14.17.0
- OS: MacOS 11.4
- Library version: 9.0.5

**Comment by nikku** [comment]
Thanks for opening this issue.

I'm not quite sure if I understand your use-case / your model and what you'd like to achieve. Why do you declare `xml:lang` as part of your package? What moddle sees is a property name that is namespaced and it does not support such thing.

If you wanted to declare `xml:lang` you'd need to define the `xml` namespace, extend any element and define the `lang` attribute there:

```
const xmlPackage = {
  name: 'xml',
  prefix: ...,
  "elements: [ {
    name: "Base",
    extends: [ "test:Base" ],
    properties: [
      {
        name: "lang",
        isAttr: true,
        type: "String"
      }
    ]
  } ]
};
```

**Comment by hanshuebner** [comment]
Hi @nikku,

thank you for your quick response and your suggestion.

The `xml:lang` attribute is the standard XML attribute that defines the language of the contents of an element.  We intend to use it to support multiple language text in the extension elements of our BPMN application.  Using the standard `xml:lang` attribute as language indicator tag would be nice, because standard methods could then be used to identify translatable strings in the XML file.

I don't quite understand your suggestion, though:  Does moddle support namespaced attributes at all?  Declaring the attribute in a different class and namespace would then make sense, i.e. our translatable model elements would then have some "Translatable" superclass and inherit the `xml:lang` attribute that way.  If moddle does not support namespaced attributes, though, we'll probably post-process the XML to convert the non-namespaced `lang` attributes to `xml:lang`. 

Thanks again,
Hans

**Comment by nikku** [comment]
Hi @hanshuebner.

Moddle does not allow you to define a property `a:foo` in the namespace `b`. This is what you're doing and it does not support it.

My [previous comment](https://github.com/bpmn-io/moddle-xml/issues/62#issuecomment-849426733) showcased how to support these built-in elements in a moddle way.

Note that moddle does roundtrip all elements it does not recognize. This means you'll be able to also query for the `xml:lang` attribute on an element via `element.get('xml:lang')` just fine. You'll also be able to set the `xml:lang` attribute via `element.set('xml:lang')` independent of whether you made moddle aware of the attribute or not.

**Comment by hanshuebner** [comment]
Hi @nikku,

thank you for your quick response again!  I will be able to work myself from here.

-Hans
