### ISSUE TITLE
Attribute is removed which creates an invalid duplicate

### ISSUE THREAD

**Issue by barmac** [bpmn-io/moddle-xml#66]
__Describe the Bug__

When imported and saved, the fragment below is transformed as in the diff:

```diff
- <triso:allowedValues constraintsType="enumeration" triso:constraintsType="enumeration">
+ <triso:allowedValues constraintsType="enumeration" constraintsType="enumeration">
```

The first fragment is validated correctly while the second one is invalid.

This breaks roundtrip of [a BPMN MIWG test case](https://github.com/bpmn-miwg/bpmn-miwg-test-suite/blob/master/Reference/C.8.1.bpmn#L1345).

__Steps to Reproduce__

See this branch: https://github.com/bpmn-io/moddle-xml/tree/duplicate-test-cases

__Expected Behavior__

Namespace should be kept.

__Environment__

- Host (Browser/Node version), if applicable: [e.g. MS Edge 18, Chrome 69, Node 10 LTS]
- OS: [e.g. Windows 7]
- Library version: [e.g. 2.0.0]

**Comment by nikku** [comment]
I honestly think that the input is already questionable XML.

Both attributes are defined in the same namespace. The second one overrides the other.

So the canonical export (fixing all things) would be:

```diff
- <triso:allowedValues constraintsType="A" triso:constraintsType="B">
+ <triso:allowedValues constraintsType="B">
```

**Comment by barmac** [comment]
I believe your proposal is even better than keeping the attributes as in the original.
